apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: sample-split-monorepo-target-only
spec:
  type: url
  owner: dhrumit
  lifecycle: experimental
  target: dir-target/target-dir-1/backstage.yaml
