apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: split-repo-with-target
spec:
  type: url
  targets:
    - ./dir-target/target-dir-1/backstage.yaml
    - ./dir-target/target-dir-2/backstage.yaml
